package Model.ConfigCheckEnum;

public enum ConfigCheckEnum {FILE_DOESNT_EXIST, DOWNLOAD_PATH_OK, WRONG_STRUCTURE, USERDATA_PATH_OK, USERDATA_PATH_WRONG, NO_HASH_CHAR_ALLOWED, HASTAGS_OK, HASTAGS_EXCEED_MAX, NOT_A_DIRECTORY}
